name: doctor_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
    
  image_picker: ^1.0.4
  firebase_storage: ^12.4.3
  auto_size_text: ^3.0.0
  firebase_core: any
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.4.1
  logger: ^2.0.2
  flutter_map_location_marker: ^8.0.3
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^4.10.0
  flutter_blue_plus: ^1.16.0
  pedometer: ^4.1.1
  permission_handler: ^11.4.0
  google_maps_flutter: ^2.10.1
  geolocator: ^11.0.0
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  latlong2: ^0.9.1
  flutter_map: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/momandbaby.png"  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/back.png
    - assets/images/man.png
    - assets/images/data.png
    - assets/images/language.png
    - assets/images/notify.png
    - assets/images/phone.png
    - assets/images/privacy.png
    - assets/images/signout.png
    - assets/images/Question.png
    - assets/images/Picture.png
    - assets/images/Setting.png
    - assets/images/Baby.png
    - assets/images/Robot.png
    - assets/images/Main.png
    - assets/images/pregnancy.png
    - assets/images/happy.png
    - assets/images/sad.png
    - assets/images/bluetooth.png
    - assets/images/tgos.png
    - assets/images/momandbaby.png
    - assets/tgos_map.html
    - assets/tgos_map.html
    - assets/map.json
    - assets/icons/icon1.jpg
    - assets/icons/icon2.png
